"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getStoredUser } from "@/lib/auth";
import { searchContent } from "@/services/content.service";
import { analyticsApi } from "@/services/analytics.service";

export default function Page(){
  const router=useRouter(); const [d,setD]=useState<any>(); const [q,setQ]=useState(""); const [results,setResults]=useState<any>(); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{const u=getStoredUser();if(!u||u.role!=="ADMIN"){router.replace("/login");return;} Promise.all([analyticsApi.adminContent(),searchContent({page:1,page_size:20})]).then(([a,r])=>{setD(a);setResults(r)}).catch(()=>setError("Unable to load content intelligence."));},[router]);
  async function search(){setLoading(true);setError("");try{const response=await searchContent({query:q,page:1,page_size:20});if(!response.success){setError(response.message||"Search failed.");return;}setResults(response);}catch{setError("Search failed. Please try again.");}finally{setLoading(false);}}
  if(!d)return <main className="p-8">Loading content intelligence…</main>;
  return <main className="mx-auto max-w-6xl px-4 py-8"><h1 className="text-3xl font-semibold">Content Intelligence</h1><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border p-5">Books <b className="block text-3xl">{d.content.books}</b></div><div className="rounded-2xl border p-5">Documents <b className="block text-3xl">{d.content.documents}</b></div><div className="rounded-2xl border p-5">Processing Jobs <b className="block text-3xl">{Object.values(d.content.ingestion_jobs || {}).reduce(
  (total: number, value: unknown) => total + Number(value),
  0
)}</b></div></div><div className="mt-8 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder="Search document content…" className="flex-1 rounded-xl border bg-background px-3 py-2"/><button disabled={loading} onClick={()=>void search()} className="rounded-xl bg-primary px-4 py-2 text-primary-foreground">{loading?"Searching…":"Search"}</button></div>{error&&<p className="mt-4 rounded-xl border border-red-300 p-3 text-sm text-red-700">{error}</p>}{results?.answer&&<section className="mt-5 rounded-2xl border bg-muted/30 p-5"><h2 className="font-semibold">Answer</h2><p className="mt-3 whitespace-pre-wrap">{results.answer}</p>{results.sources?.length>0&&<div className="mt-4 border-t pt-4"><h3 className="text-sm font-semibold">Sources</h3>{results.sources.map((s:any)=><p key={s.chunk_id} className="mt-1 text-sm text-muted-foreground">{s.document} · Page {s.page??"?"} · Chunk {s.chunk_id.slice(0,8)}</p>)}</div>}</section>}{!loading&&results?.items?.length===0&&<p className="mt-5 rounded-xl border p-4 text-sm text-muted-foreground">{results.answer||"No relevant document content found."}</p>}<section className="mt-5 space-y-3">{results?.items?.map((x:any)=><div key={x.chunk_id} className="rounded-2xl border p-4"><div className="flex justify-between gap-4"><div><a href={`/admin/content/${x.document_id}`} className="font-semibold underline">{x.document_title}</a><p className="text-sm text-muted-foreground">{x.book_title} · {x.chapter_title || "No chapter"} · Pages {x.page_start ?? "?"}{x.page_end && x.page_end!==x.page_start?`–${x.page_end}`:""} · {x.language}</p></div><span className="text-xs text-muted-foreground">chunk {x.chunk_id.slice(0,8)}</span></div><p className="mt-3 line-clamp-4 text-sm">{x.content}</p></div>)}</section></main>
}
